//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 12:13:54 PM WEST 
//


package com.ckwanted.user;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ckwanted.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ckwanted.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Usuario.User.RdfMapping }
     * 
     */
    public Usuario.User.RdfMapping createResultUserRdfMapping() {
        return new Usuario.User.RdfMapping();
    }

    /**
     * Create an instance of {@link Usuario.User.OgUserNode }
     * 
     */
    public Usuario.User.OgUserNode createResultUserOgUserNode() {
        return new Usuario.User.OgUserNode();
    }

    /**
     * Create an instance of {@link Usuario.User.Roles }
     * 
     */
    public Usuario.User.Roles createResultUserRoles() {
        return new Usuario.User.Roles();
    }

    /**
     * Create an instance of {@link Usuario.User }
     * 
     */
    public Usuario.User createResultUser() {
        return new Usuario.User();
    }

    /**
     * Create an instance of {@link Usuario.User.RdfMapping.Homepage.Predicates }
     * 
     */
    public Usuario.User.RdfMapping.Homepage.Predicates createResultUserRdfMappingHomepagePredicates() {
        return new Usuario.User.RdfMapping.Homepage.Predicates();
    }

    /**
     * Create an instance of {@link Usuario.User.Data }
     * 
     */
    public Usuario.User.Data createResultUserData() {
        return new Usuario.User.Data();
    }

    /**
     * Create an instance of {@link Usuario.User.RdfMapping.Name.Predicates }
     * 
     */
    public Usuario.User.RdfMapping.Name.Predicates createResultUserRdfMappingNamePredicates() {
        return new Usuario.User.RdfMapping.Name.Predicates();
    }

    /**
     * Create an instance of {@link Usuario.User.OgUserNode.Und.Item }
     * 
     */
    public Usuario.User.OgUserNode.Und.Item createResultUserOgUserNodeUndItem() {
        return new Usuario.User.OgUserNode.Und.Item();
    }

    /**
     * Create an instance of {@link Usuario.User.RdfMapping.Rdftype }
     * 
     */
    public Usuario.User.RdfMapping.Rdftype createResultUserRdfMappingRdftype() {
        return new Usuario.User.RdfMapping.Rdftype();
    }

    /**
     * Create an instance of {@link Usuario.User.RdfMapping.Homepage }
     * 
     */
    public Usuario.User.RdfMapping.Homepage createResultUserRdfMappingHomepage() {
        return new Usuario.User.RdfMapping.Homepage();
    }

    /**
     * Create an instance of {@link Usuario.User.OgUserNode.Und }
     * 
     */
    public Usuario.User.OgUserNode.Und createResultUserOgUserNodeUnd() {
        return new Usuario.User.OgUserNode.Und();
    }

    /**
     * Create an instance of {@link Usuario.User.RdfMapping.Name }
     * 
     */
    public Usuario.User.RdfMapping.Name createResultUserRdfMappingName() {
        return new Usuario.User.RdfMapping.Name();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createResult() {
        return new Usuario();
    }

}
