//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 12:13:54 PM WEST 
//


package com.ckwanted.user;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sessid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="session_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="theme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="signature_format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="access" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="init" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="data">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ckeditor_default" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ckeditor_show_toggle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ckeditor_width" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ckeditor_lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ckeditor_auto_lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="overlay" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="roles">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="og_user_node">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="und">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="target_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="rdf_mapping">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="rdftype">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="name">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="predicates">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="homepage">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="predicates">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessid",
    "sessionName",
    "token",
    "user"
})
@XmlRootElement(name = "result")
public class Usuario {

    @XmlElement(required = true)
    protected String sessid;
    @XmlElement(name = "session_name", required = true)
    protected String sessionName;
    @XmlElement(required = true)
    protected String token;
    @XmlElement(required = true)
    protected Usuario.User user;

    /**
     * Gets the value of the sessid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessid() {
        return sessid;
    }

    /**
     * Sets the value of the sessid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessid(String value) {
        this.sessid = value;
    }

    /**
     * Gets the value of the sessionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionName() {
        return sessionName;
    }

    /**
     * Sets the value of the sessionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionName(String value) {
        this.sessionName = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link Usuario.User }
     *     
     */
    public Usuario.User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usuario.User }
     *     
     */
    public void setUser(Usuario.User value) {
        this.user = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="theme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="signature_format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="created" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="access" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="picture" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="init" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="data">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ckeditor_default" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ckeditor_show_toggle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ckeditor_width" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ckeditor_lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ckeditor_auto_lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="overlay" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="roles">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="og_user_node">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="und">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="target_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="rdf_mapping">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="rdftype">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="name">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="predicates">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="homepage">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="predicates">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid",
        "name",
        "mail",
        "theme",
        "signature",
        "signatureFormat",
        "created",
        "access",
        "login",
        "status",
        "timezone",
        "language",
        "picture",
        "init",
        "data",
        "roles",
        "ogUserNode",
        "rdfMapping"
    })
    public static class User {

        protected byte uid;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String mail;
        @XmlElement(required = true)
        protected String theme;
        @XmlElement(required = true)
        protected String signature;
        @XmlElement(name = "signature_format", required = true)
        protected String signatureFormat;
        protected int created;
        protected int access;
        protected int login;
        protected byte status;
        @XmlElement(required = true)
        protected String timezone;
        @XmlElement(required = true)
        protected String language;
        @XmlElement(required = true)
        protected String picture;
        @XmlElement(required = true)
        protected String init;
        @XmlElement(required = true)
        protected Usuario.User.Data data;
        @XmlElement(required = true)
        protected Usuario.User.Roles roles;
        @XmlElement(name = "og_user_node", required = true)
        protected Usuario.User.OgUserNode ogUserNode;
        @XmlElement(name = "rdf_mapping", required = true)
        protected Usuario.User.RdfMapping rdfMapping;

        /**
         * Gets the value of the uid property.
         * 
         */
        public byte getUid() {
            return uid;
        }

        /**
         * Sets the value of the uid property.
         * 
         */
        public void setUid(byte value) {
            this.uid = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the mail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMail() {
            return mail;
        }

        /**
         * Sets the value of the mail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMail(String value) {
            this.mail = value;
        }

        /**
         * Gets the value of the theme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTheme() {
            return theme;
        }

        /**
         * Sets the value of the theme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTheme(String value) {
            this.theme = value;
        }

        /**
         * Gets the value of the signature property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignature() {
            return signature;
        }

        /**
         * Sets the value of the signature property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignature(String value) {
            this.signature = value;
        }

        /**
         * Gets the value of the signatureFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignatureFormat() {
            return signatureFormat;
        }

        /**
         * Sets the value of the signatureFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignatureFormat(String value) {
            this.signatureFormat = value;
        }

        /**
         * Gets the value of the created property.
         * 
         */
        public int getCreated() {
            return created;
        }

        /**
         * Sets the value of the created property.
         * 
         */
        public void setCreated(int value) {
            this.created = value;
        }

        /**
         * Gets the value of the access property.
         * 
         */
        public int getAccess() {
            return access;
        }

        /**
         * Sets the value of the access property.
         * 
         */
        public void setAccess(int value) {
            this.access = value;
        }

        /**
         * Gets the value of the login property.
         * 
         */
        public int getLogin() {
            return login;
        }

        /**
         * Sets the value of the login property.
         * 
         */
        public void setLogin(int value) {
            this.login = value;
        }

        /**
         * Gets the value of the status property.
         * 
         */
        public byte getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         */
        public void setStatus(byte value) {
            this.status = value;
        }

        /**
         * Gets the value of the timezone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimezone() {
            return timezone;
        }

        /**
         * Sets the value of the timezone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimezone(String value) {
            this.timezone = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the picture property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPicture() {
            return picture;
        }

        /**
         * Sets the value of the picture property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPicture(String value) {
            this.picture = value;
        }

        /**
         * Gets the value of the init property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInit() {
            return init;
        }

        /**
         * Sets the value of the init property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInit(String value) {
            this.init = value;
        }

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link Usuario.User.Data }
         *     
         */
        public Usuario.User.Data getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link Usuario.User.Data }
         *     
         */
        public void setData(Usuario.User.Data value) {
            this.data = value;
        }

        /**
         * Gets the value of the roles property.
         * 
         * @return
         *     possible object is
         *     {@link Usuario.User.Roles }
         *     
         */
        public Usuario.User.Roles getRoles() {
            return roles;
        }

        /**
         * Sets the value of the roles property.
         * 
         * @param value
         *     allowed object is
         *     {@link Usuario.User.Roles }
         *     
         */
        public void setRoles(Usuario.User.Roles value) {
            this.roles = value;
        }

        /**
         * Gets the value of the ogUserNode property.
         * 
         * @return
         *     possible object is
         *     {@link Usuario.User.OgUserNode }
         *     
         */
        public Usuario.User.OgUserNode getOgUserNode() {
            return ogUserNode;
        }

        /**
         * Sets the value of the ogUserNode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Usuario.User.OgUserNode }
         *     
         */
        public void setOgUserNode(Usuario.User.OgUserNode value) {
            this.ogUserNode = value;
        }

        /**
         * Gets the value of the rdfMapping property.
         * 
         * @return
         *     possible object is
         *     {@link Usuario.User.RdfMapping }
         *     
         */
        public Usuario.User.RdfMapping getRdfMapping() {
            return rdfMapping;
        }

        /**
         * Sets the value of the rdfMapping property.
         * 
         * @param value
         *     allowed object is
         *     {@link Usuario.User.RdfMapping }
         *     
         */
        public void setRdfMapping(Usuario.User.RdfMapping value) {
            this.rdfMapping = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ckeditor_default" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ckeditor_show_toggle" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ckeditor_width" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ckeditor_lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ckeditor_auto_lang" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="overlay" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ckeditorDefault",
            "ckeditorShowToggle",
            "ckeditorWidth",
            "ckeditorLang",
            "ckeditorAutoLang",
            "overlay"
        })
        public static class Data {

            @XmlElement(name = "ckeditor_default", required = true)
            protected String ckeditorDefault;
            @XmlElement(name = "ckeditor_show_toggle", required = true)
            protected String ckeditorShowToggle;
            @XmlElement(name = "ckeditor_width", required = true)
            protected String ckeditorWidth;
            @XmlElement(name = "ckeditor_lang", required = true)
            protected String ckeditorLang;
            @XmlElement(name = "ckeditor_auto_lang", required = true)
            protected String ckeditorAutoLang;
            protected byte overlay;

            /**
             * Gets the value of the ckeditorDefault property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCkeditorDefault() {
                return ckeditorDefault;
            }

            /**
             * Sets the value of the ckeditorDefault property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCkeditorDefault(String value) {
                this.ckeditorDefault = value;
            }

            /**
             * Gets the value of the ckeditorShowToggle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCkeditorShowToggle() {
                return ckeditorShowToggle;
            }

            /**
             * Sets the value of the ckeditorShowToggle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCkeditorShowToggle(String value) {
                this.ckeditorShowToggle = value;
            }

            /**
             * Gets the value of the ckeditorWidth property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCkeditorWidth() {
                return ckeditorWidth;
            }

            /**
             * Sets the value of the ckeditorWidth property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCkeditorWidth(String value) {
                this.ckeditorWidth = value;
            }

            /**
             * Gets the value of the ckeditorLang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCkeditorLang() {
                return ckeditorLang;
            }

            /**
             * Sets the value of the ckeditorLang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCkeditorLang(String value) {
                this.ckeditorLang = value;
            }

            /**
             * Gets the value of the ckeditorAutoLang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCkeditorAutoLang() {
                return ckeditorAutoLang;
            }

            /**
             * Sets the value of the ckeditorAutoLang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCkeditorAutoLang(String value) {
                this.ckeditorAutoLang = value;
            }

            /**
             * Gets the value of the overlay property.
             * 
             */
            public byte getOverlay() {
                return overlay;
            }

            /**
             * Sets the value of the overlay property.
             * 
             */
            public void setOverlay(byte value) {
                this.overlay = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="und">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="target_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "und"
        })
        public static class OgUserNode {

            @XmlElement(required = true)
            protected Usuario.User.OgUserNode.Und und;

            /**
             * Gets the value of the und property.
             * 
             * @return
             *     possible object is
             *     {@link Usuario.User.OgUserNode.Und }
             *     
             */
            public Usuario.User.OgUserNode.Und getUnd() {
                return und;
            }

            /**
             * Sets the value of the und property.
             * 
             * @param value
             *     allowed object is
             *     {@link Usuario.User.OgUserNode.Und }
             *     
             */
            public void setUnd(Usuario.User.OgUserNode.Und value) {
                this.und = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="target_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "item"
            })
            public static class Und {

                protected List<Usuario.User.OgUserNode.Und.Item> item;
                @XmlAttribute(name = "is_array")
                protected String isArray;

                /**
                 * Gets the value of the item property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the item property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getItem().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Usuario.User.OgUserNode.Und.Item }
                 * 
                 * 
                 */
                public List<Usuario.User.OgUserNode.Und.Item> getItem() {
                    if (item == null) {
                        item = new ArrayList<Usuario.User.OgUserNode.Und.Item>();
                    }
                    return this.item;
                }

                /**
                 * Gets the value of the isArray property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsArray() {
                    return isArray;
                }

                /**
                 * Sets the value of the isArray property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsArray(String value) {
                    this.isArray = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="target_id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "targetId"
                })
                public static class Item {

                    @XmlElement(name = "target_id")
                    protected byte targetId;

                    /**
                     * Gets the value of the targetId property.
                     * 
                     */
                    public byte getTargetId() {
                        return targetId;
                    }

                    /**
                     * Sets the value of the targetId property.
                     * 
                     */
                    public void setTargetId(byte value) {
                        this.targetId = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="rdftype">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="name">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="predicates">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="homepage">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="predicates">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rdftype",
            "name",
            "homepage"
        })
        public static class RdfMapping {

            @XmlElement(required = true)
            protected Usuario.User.RdfMapping.Rdftype rdftype;
            @XmlElement(required = true)
            protected Usuario.User.RdfMapping.Name name;
            @XmlElement(required = true)
            protected Usuario.User.RdfMapping.Homepage homepage;

            /**
             * Gets the value of the rdftype property.
             * 
             * @return
             *     possible object is
             *     {@link Usuario.User.RdfMapping.Rdftype }
             *     
             */
            public Usuario.User.RdfMapping.Rdftype getRdftype() {
                return rdftype;
            }

            /**
             * Sets the value of the rdftype property.
             * 
             * @param value
             *     allowed object is
             *     {@link Usuario.User.RdfMapping.Rdftype }
             *     
             */
            public void setRdftype(Usuario.User.RdfMapping.Rdftype value) {
                this.rdftype = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link Usuario.User.RdfMapping.Name }
             *     
             */
            public Usuario.User.RdfMapping.Name getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link Usuario.User.RdfMapping.Name }
             *     
             */
            public void setName(Usuario.User.RdfMapping.Name value) {
                this.name = value;
            }

            /**
             * Gets the value of the homepage property.
             * 
             * @return
             *     possible object is
             *     {@link Usuario.User.RdfMapping.Homepage }
             *     
             */
            public Usuario.User.RdfMapping.Homepage getHomepage() {
                return homepage;
            }

            /**
             * Sets the value of the homepage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Usuario.User.RdfMapping.Homepage }
             *     
             */
            public void setHomepage(Usuario.User.RdfMapping.Homepage value) {
                this.homepage = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="predicates">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "predicates",
                "type"
            })
            public static class Homepage {

                @XmlElement(required = true)
                protected Usuario.User.RdfMapping.Homepage.Predicates predicates;
                @XmlElement(required = true)
                protected String type;

                /**
                 * Gets the value of the predicates property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Usuario.User.RdfMapping.Homepage.Predicates }
                 *     
                 */
                public Usuario.User.RdfMapping.Homepage.Predicates getPredicates() {
                    return predicates;
                }

                /**
                 * Sets the value of the predicates property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Usuario.User.RdfMapping.Homepage.Predicates }
                 *     
                 */
                public void setPredicates(Usuario.User.RdfMapping.Homepage.Predicates value) {
                    this.predicates = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "item"
                })
                public static class Predicates {

                    @XmlElement(required = true)
                    protected String item;
                    @XmlAttribute(name = "is_array")
                    protected String isArray;

                    /**
                     * Gets the value of the item property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getItem() {
                        return item;
                    }

                    /**
                     * Sets the value of the item property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setItem(String value) {
                        this.item = value;
                    }

                    /**
                     * Gets the value of the isArray property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIsArray() {
                        return isArray;
                    }

                    /**
                     * Sets the value of the isArray property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIsArray(String value) {
                        this.isArray = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="predicates">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "predicates"
            })
            public static class Name {

                @XmlElement(required = true)
                protected Usuario.User.RdfMapping.Name.Predicates predicates;

                /**
                 * Gets the value of the predicates property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Usuario.User.RdfMapping.Name.Predicates }
                 *     
                 */
                public Usuario.User.RdfMapping.Name.Predicates getPredicates() {
                    return predicates;
                }

                /**
                 * Sets the value of the predicates property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Usuario.User.RdfMapping.Name.Predicates }
                 *     
                 */
                public void setPredicates(Usuario.User.RdfMapping.Name.Predicates value) {
                    this.predicates = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "item"
                })
                public static class Predicates {

                    @XmlElement(required = true)
                    protected String item;
                    @XmlAttribute(name = "is_array")
                    protected String isArray;

                    /**
                     * Gets the value of the item property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getItem() {
                        return item;
                    }

                    /**
                     * Sets the value of the item property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setItem(String value) {
                        this.item = value;
                    }

                    /**
                     * Gets the value of the isArray property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIsArray() {
                        return isArray;
                    }

                    /**
                     * Sets the value of the isArray property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIsArray(String value) {
                        this.isArray = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "item"
            })
            public static class Rdftype {

                @XmlElement(required = true)
                protected String item;
                @XmlAttribute(name = "is_array")
                protected String isArray;

                /**
                 * Gets the value of the item property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getItem() {
                    return item;
                }

                /**
                 * Sets the value of the item property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setItem(String value) {
                    this.item = value;
                }

                /**
                 * Gets the value of the isArray property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIsArray() {
                    return isArray;
                }

                /**
                 * Sets the value of the isArray property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIsArray(String value) {
                    this.isArray = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="item" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="is_array" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class Roles {

            protected List<String> item;
            @XmlAttribute(name = "is_array")
            protected String isArray;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getItem() {
                if (item == null) {
                    item = new ArrayList<String>();
                }
                return this.item;
            }

            /**
             * Gets the value of the isArray property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsArray() {
                return isArray;
            }

            /**
             * Sets the value of the isArray property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsArray(String value) {
                this.isArray = value;
            }

        }

    }

}
