//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 12:03:44 PM WEST 
//


package com.ckwanted.receta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ckwanted.receta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ckwanted.receta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Body }
     * 
     */
    public Receta.RdfMapping.Body createResultRdfMappingBody() {
        return new Receta.RdfMapping.Body();
    }

    /**
     * Create an instance of {@link Receta.Body }
     * 
     */
    public Receta.Body createResultBody() {
        return new Receta.Body();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Body.Predicates }
     * 
     */
    public Receta.RdfMapping.Body.Predicates createResultRdfMappingBodyPredicates() {
        return new Receta.RdfMapping.Body.Predicates();
    }

    /**
     * Create an instance of {@link Receta.FieldDificultad.Und }
     * 
     */
    public Receta.FieldDificultad.Und createResultFieldDificultadUnd() {
        return new Receta.FieldDificultad.Und();
    }

    /**
     * Create an instance of {@link Receta.FieldImagen }
     * 
     */
    public Receta.FieldImagen createResultFieldImagen() {
        return new Receta.FieldImagen();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.LastActivity }
     * 
     */
    public Receta.RdfMapping.LastActivity createResultRdfMappingLastActivity() {
        return new Receta.RdfMapping.LastActivity();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Name.Predicates }
     * 
     */
    public Receta.RdfMapping.Name.Predicates createResultRdfMappingNamePredicates() {
        return new Receta.RdfMapping.Name.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Name }
     * 
     */
    public Receta.RdfMapping.Name createResultRdfMappingName() {
        return new Receta.RdfMapping.Name();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Title }
     * 
     */
    public Receta.RdfMapping.Title createResultRdfMappingTitle() {
        return new Receta.RdfMapping.Title();
    }

    /**
     * Create an instance of {@link Receta.FieldDificultad }
     * 
     */
    public Receta.FieldDificultad createResultFieldDificultad() {
        return new Receta.FieldDificultad();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Uid.Predicates }
     * 
     */
    public Receta.RdfMapping.Uid.Predicates createResultRdfMappingUidPredicates() {
        return new Receta.RdfMapping.Uid.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.LastActivity.Predicates }
     * 
     */
    public Receta.RdfMapping.LastActivity.Predicates createResultRdfMappingLastActivityPredicates() {
        return new Receta.RdfMapping.LastActivity.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Changed.Predicates }
     * 
     */
    public Receta.RdfMapping.Changed.Predicates createResultRdfMappingChangedPredicates() {
        return new Receta.RdfMapping.Changed.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping }
     * 
     */
    public Receta.RdfMapping createResultRdfMapping() {
        return new Receta.RdfMapping();
    }

    /**
     * Create an instance of {@link Receta.FieldImagen.Und.Item }
     * 
     */
    public Receta.FieldImagen.Und.Item createResultFieldImagenUndItem() {
        return new Receta.FieldImagen.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Uid }
     * 
     */
    public Receta.RdfMapping.Uid createResultRdfMappingUid() {
        return new Receta.RdfMapping.Uid();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Changed }
     * 
     */
    public Receta.RdfMapping.Changed createResultRdfMappingChanged() {
        return new Receta.RdfMapping.Changed();
    }

    /**
     * Create an instance of {@link Receta }
     * 
     */
    public Receta createResult() {
        return new Receta();
    }

    /**
     * Create an instance of {@link Receta.Body.Und }
     * 
     */
    public Receta.Body.Und createResultBodyUnd() {
        return new Receta.Body.Und();
    }

    /**
     * Create an instance of {@link Receta.OgGroupRef.Und }
     * 
     */
    public Receta.OgGroupRef.Und createResultOgGroupRefUnd() {
        return new Receta.OgGroupRef.Und();
    }

    /**
     * Create an instance of {@link Receta.FieldDificultad.Und.Item }
     * 
     */
    public Receta.FieldDificultad.Und.Item createResultFieldDificultadUndItem() {
        return new Receta.FieldDificultad.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.OgGroupRef.Und.Item }
     * 
     */
    public Receta.OgGroupRef.Und.Item createResultOgGroupRefUndItem() {
        return new Receta.OgGroupRef.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Rdftype }
     * 
     */
    public Receta.RdfMapping.Rdftype createResultRdfMappingRdftype() {
        return new Receta.RdfMapping.Rdftype();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Title.Predicates }
     * 
     */
    public Receta.RdfMapping.Title.Predicates createResultRdfMappingTitlePredicates() {
        return new Receta.RdfMapping.Title.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.CommentCount }
     * 
     */
    public Receta.RdfMapping.CommentCount createResultRdfMappingCommentCount() {
        return new Receta.RdfMapping.CommentCount();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Created.Predicates }
     * 
     */
    public Receta.RdfMapping.Created.Predicates createResultRdfMappingCreatedPredicates() {
        return new Receta.RdfMapping.Created.Predicates();
    }

    /**
     * Create an instance of {@link Receta.Body.Und.Item }
     * 
     */
    public Receta.Body.Und.Item createResultBodyUndItem() {
        return new Receta.Body.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Created }
     * 
     */
    public Receta.RdfMapping.Created createResultRdfMappingCreated() {
        return new Receta.RdfMapping.Created();
    }

    /**
     * Create an instance of {@link Receta.OgGroupRef }
     * 
     */
    public Receta.OgGroupRef createResultOgGroupRef() {
        return new Receta.OgGroupRef();
    }

    /**
     * Create an instance of {@link Receta.FieldImagen.Und }
     * 
     */
    public Receta.FieldImagen.Und createResultFieldImagenUnd() {
        return new Receta.FieldImagen.Und();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.CommentCount.Predicates }
     * 
     */
    public Receta.RdfMapping.CommentCount.Predicates createResultRdfMappingCommentCountPredicates() {
        return new Receta.RdfMapping.CommentCount.Predicates();
    }

}
